Realizado registro de usuarios y tests-#99
youRoom-ISPP/youRoom pull request #111
Opened 2021-04-08 17:44 UTC by alfgonfer

Se ha realizado el backend de registro de usuarios y una serie de tests para probar los distintos casos: la contraseña debe coincidir, no puede haber dos usuarios con el mismo username y no puede haber dos usuarios con el mismo correo.
La integración de backend-frontend se realizará en la rama correspondiente al frontend de registro.

2021-04-09 10:54 UTC, jorandmol approved these changes
Veo todo correcto. Habrá que hacer pequeñas modificaciones en el controlador de usuario para que se realice correctamente la opción de registro.

2021-04-09 11:12 UTC, jorandmol requested changes
Habría que mezclar los controladores de registro y login para que sean uno solo. De esta forma integramos las dos funcionalidades en la vista de login, haciendo que quede más limpio.

2021-04-09 15:00 UTC, jorandmol reviewed
Cambio de opinión; está todo bien. Únicamente necesitaría que se enviase el listado de usernames para validar en la interfaz que el cliente no está introduciendo uno ya existente.

2021-04-09 15:01 UTC, jorandmol approved these changes

2021-04-10 07:15 UTC, mrf1989 requested changes
Se os ha colado el registro.html en el commit. Lo suyo sería dejarlo fuera para que no entre en conflicto con el trabajo de @jorandmol

2021-04-10 07:53 UTC, jorandmol commented
> Se os ha colado el registro.html en el commit. Lo suyo sería dejarlo fuera para que no entre en conflicto con el trabajo de @jorandmol

Parece que es por la necesidad de que pasen algunos test. No debe de haber problema ya que está controlando.

Una vez se añadan estos cambios en la rama develop me encargaré de integrar frontend y backend en la rama de la tarea #98

2021-04-10 07:53 UTC, fragonlug commented
> Se os ha colado el registro.html en el commit. Lo suyo sería dejarlo fuera para que no entre en conflicto con el trabajo de @jorandmol

Es necesario que exista para la realización de los test del registro, se espera que cuando se integre con el frontend, sea sustituido por completo, teniendo así 0 impacto sobre el trabajo realizado de @jorandmol .

2021-04-10 08:03 UTC, mrf1989 approved these changes

2021-04-10 08:22 UTC, merged