Listado y búsqueda de usuarios-#132
youRoom-ISPP/youRoom pull request #136
Opened 2021-04-18 15:52 UTC by alemunara

Finalizado el buscador de usuarios y la visualización del perfil de otros usuarios

2021-04-18 20:18 UTC, fragonlug approved these changes
Se ha validado el funcionamiento del nuevo caso de uso

2021-04-18 20:55 UTC, jorandmol requested changes
He comprobado que funciona todo bien excepto que el usuario no puede votar desde el perfil de otro usuario. Aparecen las estrellas, por lo que tiene posibilidad, pero no se realiza la votación.

O quitaría dicha opción o lo arreglaría.

2021-04-19 09:09 UTC, alemunara commented
Se ha corregido el error identificado al valorar publicaciones

2021-04-19 10:35 UTC, jorandmol approved these changes
He comprobado que se puede valorar desde la vista de usuarios, por lo que apruebo la petición.

2021-04-19 10:36 UTC, merged