AU: Autenticación del usuario
youRoom-ISPP/youRoom pull request #22
Opened 2021-03-20 17:02 UTC by fragonlug

Se han creado los modelos correspondientes para el usuario de la aplicación y se ha implementado el login y logout de la aplicación.

2021-03-20 17:08 UTC, ferruirob commented
La rama tiene errores detectados por codacy, hasta que no pase los pase no puedo aceptar el merge.  Arregla los errores por favor. Gracias [https://app.codacy.com/gh/youRoom-ISPP/youRoom/pullRequest?prid=7131144#newIssuesView]

2021-03-20 17:23 UTC, fragonlug commented
> La rama tiene errores detectados por codacy, hasta que no pase los pase no puedo aceptar el merge. Arregla los errores por favor. Gracias [https://app.codacy.com/gh/youRoom-ISPP/youRoom/pullRequest?prid=7131144#newIssuesView]

Se han realizado los cambios pertinentes en respuesta a estas incidencias.

2021-03-21 11:54 UTC, mrf1989 commented on youroom/usuario/urls.py
> +    path('', include(timeline_urls), name='home'),
@fragonlug  Es importante que el name no tenga una referencia errónea o que no corresponde con los términos utilizados en el proyecto. En este caso, name tendría que tener el valor "timeline".

2021-03-21 11:56 UTC, mrf1989 commented on youroom/youroom/settings.py
> +LOGIN_REDIRECT_URL = 'home'
@fragonlug Lo mismo digo, la redirección del login no se hace a la "home", que no tenemos como tal, sino al "timeline".

2021-03-21 11:57 UTC, mrf1989 commented on youroom/usuario/tests.py
> +
@fragonlug Estaría bien contar con un test de caso negativo.

2021-03-21 11:58 UTC, mrf1989 requested changes
@fragonlug Te dejo algunos comentarios en sus correspondientes líneas que tendrían que resolverse para no arrastrar cosas a la línea de desarrollo.

Las hemos hablado antes.

2021-03-21 13:28 UTC, fragonlug commented
> @fragonlug Te dejo algunos comentarios en sus correspondientes líneas que tendrían que resolverse para no arrastrar cosas a la línea de desarrollo.
> 
> Las hemos hablado antes.

Se han tomado en cuenta las anotaciones y se han realizado los cambios pertinentes.

2021-03-21 13:31 UTC, mrf1989 approved these changes
Perfecto! Por mi parte, nada más que añadir.

2021-03-21 13:52 UTC, ferruirob commented
Revisado y todo correcto. Apruebo el merge request por mi parte también.

2021-03-21 13:55 UTC, merged