Solucionado el fallo al mostrar nombres de usuario en timeline - #43
youRoom-ISPP/youRoom pull request #45
Opened 2021-03-25 10:30 UTC by juacormun

Corregida la variable usada en la línea 31 de `timeline.html` para que los nombres de usuario se muestren correctamente en cada tarjeta de publicación.

2021-03-25 16:54 UTC, fragonlug approved these changes
Se ha seguido la solución propuesta, con lo que cuenta con mi aprobación.

2021-03-25 20:45 UTC, mrf1989 commented
@juacormun Revisa el conflicto de código que hay generado, por favor.

2021-03-25 20:46 UTC, mrf1989 requested changes
Se generó conflicto de código que debe resolverse.

2021-03-26 10:13 UTC, mrf1989 commented
@juacormun Dado que la incidencia esta se resuelve cambiando una línea, cancelo dicha incidencia y queda absorbida por la incidencia de la develop.

2021-03-26 10:13 UTC, closed without merging