PU: Visualizar perfil de usuario-#11
youRoom-ISPP/youRoom pull request #46
Opened 2021-03-25 11:27 UTC by javsolgar

Se ha implementado la consulta de un perfil por parte de un usuario y se han generado pruebas para comprobar su correcto funcionamiento Closes #11 .

Por otra parte, se ha realizado una pequeña modificación en el test de publicación para solucionar un problema de consulta a la base de datos #9 .

2021-03-25 17:04 UTC, fragonlug approved these changes
Se ha observado que se lista las publicación correctamente asociadas al usuario, estando pendientes su correcta visualización, teniendo en cuenta que deberían aparecer primero las más reciente, pero se comprende que forma parte del equipo de frontend.

2021-03-25 20:41 UTC, mrf1989 requested changes
La parte frontend no se debería tocar ni verse afectada por los progresos. Lo que se avance de un lado no puede ir en detrimento de otro.

Metedle una revisada, por favor.

2021-03-25 20:41 UTC, mrf1989 commented on youroom/templates/perfil/perfil.html
> +                        <p>{{usuario.descripcion}} <br> Contacto: diseño@diseño.com <br> Mi tienda: miTienda.com</p>
No entiendo estos cambios ni tampoco estos estáticos como "contacto" o "mi tienda".

Además, insisto, aquí se le está metiendo mano a parte de frontend en una tarea de backend. Cuidado porque al desplegar la app y navegar a /perfil las publicaciones se rompen y las etiquetas ya no aparecen correctamente.

2021-03-25 20:55 UTC, javsolgar commented on youroom/templates/perfil/perfil.html
> +                        <p>{{usuario.descripcion}} <br> Contacto: diseño@diseño.com <br> Mi tienda: miTienda.com</p>
Según he hablado con mis compañeros, lo de la tienda es un residuo que ya estaban en la template y que no quisieron cambiar para no molestar a los de frontend. Ellos solo quisieron probar si funcionaba el código que hicieron en backend. Igualmente si lo ves adecuado, podemos dejar simplemente el contenido que hay en develop.

2021-03-26 07:05 UTC, mrf1989 commented on youroom/templates/perfil/perfil.html
> +                        <p>{{usuario.descripcion}} <br> Contacto: diseño@diseño.com <br> Mi tienda: miTienda.com</p>
@javsolgar Entiendo que, a veces, programar el backend es complicado porque se necesita tener una confirmación visual de que la implementación es correcta y hace lo que se espera. También para ello están los tests. Pero si de todos modos los tests fueran insuficientes y no se tiene la seguridad de que lo que está hecho está bien sin verlo, ok, se puede tocar el frontend, pero no commitear esa parte.

Finalmente esos archivos no deberían formar parte del commit, ya que podría trastocar trabajo hecho y consumir un tiempo de trabajo que debería emplearse solo a integrar o resolver la integración.

2021-03-26 08:08 UTC, javsolgar commented on youroom/templates/perfil/perfil.html
> +                        <p>{{usuario.descripcion}} <br> Contacto: diseño@diseño.com <br> Mi tienda: miTienda.com</p>
De acuerdo, tomamos nota y realizamos un nuevo commit a la rama cumpliendo con los cambios que nos has solicitado. ¡Muchas gracias!

2021-03-26 08:38 UTC, javsolgar commented
Se ha dejado el contenido de perfil.html exactamente igual que en develop.

2021-03-26 10:41 UTC, mrf1989 approved these changes

2021-03-26 10:41 UTC, merged